export const COVERAGE_CODES = ['O', 'S', 'D', 'N'] as const;

export type CoverageCode = (typeof COVERAGE_CODES)[number];

export type GlobalServiceLocation = {
  id: string;
  name: string;
  country: string;
  code?: string;
  latitude: number;
  longitude: number;
  coverage: readonly CoverageCode[];
  countryLevel?: boolean;
};

export const GLOBAL_SERVICE_LOCATIONS: readonly GlobalServiceLocation[] = [
  {
    id: 'taipei-tpe',
    name: 'Taipei',
    country: 'Taiwan',
    code: 'TPE',
    latitude: 25.033,
    longitude: 121.5654,
    coverage: ['O', 'S', 'N'],
  },
  {
    id: 'taichung',
    name: 'Taichung',
    country: 'Taiwan',
    latitude: 24.1477,
    longitude: 120.6736,
    coverage: ['O', 'S'],
  },
  {
    id: 'kaohsiung',
    name: 'Kaohsiung',
    country: 'Taiwan',
    latitude: 22.6273,
    longitude: 120.3014,
    coverage: ['O', 'S'],
  },
  {
    id: 'hsinchu',
    name: 'Hsinchu',
    country: 'Taiwan',
    latitude: 24.8138,
    longitude: 120.9675,
    coverage: ['O'],
  },
  {
    id: 'taoyuan',
    name: 'Taoyuan',
    country: 'Taiwan',
    latitude: 24.9937,
    longitude: 121.301,
    coverage: ['O', 'S'],
  },
  {
    id: 'keelung',
    name: 'Keelung',
    country: 'Taiwan',
    latitude: 25.1276,
    longitude: 121.7392,
    coverage: ['S'],
  },

  {
    id: 'hong-kong-hkg',
    name: 'Hong Kong',
    country: 'Hong Kong',
    code: 'HKG',
    latitude: 22.3193,
    longitude: 114.1694,
    coverage: ['O', 'S', 'D', 'N'],
  },
  {
    id: 'xiamen',
    name: 'Xiamen',
    country: 'China',
    latitude: 24.4798,
    longitude: 118.0894,
    coverage: ['O', 'S'],
  },
  {
    id: 'shenzhen-szx',
    name: 'Shenzhen',
    country: 'China',
    code: 'SZX',
    latitude: 22.5431,
    longitude: 114.0579,
    coverage: ['O', 'N'],
  },
  {
    id: 'guangzhou',
    name: 'Guangzhou',
    country: 'China',
    latitude: 23.1291,
    longitude: 113.2644,
    coverage: ['O'],
  },
  {
    id: 'zhongshan',
    name: 'Zhongshan',
    country: 'China',
    latitude: 22.5176,
    longitude: 113.3928,
    coverage: ['O'],
  },
  {
    id: 'dongguan',
    name: 'Dongguan',
    country: 'China',
    latitude: 23.0207,
    longitude: 113.7518,
    coverage: ['O'],
  },
  {
    id: 'foshan',
    name: 'Foshan',
    country: 'China',
    latitude: 23.0215,
    longitude: 113.1214,
    coverage: ['O'],
  },
  {
    id: 'shanghai-pvg',
    name: 'Shanghai / Pudong',
    country: 'China',
    code: 'PVG',
    latitude: 31.2304,
    longitude: 121.4737,
    coverage: ['O', 'S', 'N'],
  },
  {
    id: 'suzhou',
    name: 'Suzhou',
    country: 'China',
    latitude: 31.2989,
    longitude: 120.5853,
    coverage: ['O'],
  },
  {
    id: 'qingdao',
    name: 'Qingdao',
    country: 'China',
    latitude: 36.0671,
    longitude: 120.3826,
    coverage: ['O', 'S'],
  },
  {
    id: 'ningbo',
    name: 'Ningbo',
    country: 'China',
    latitude: 29.8683,
    longitude: 121.544,
    coverage: ['O'],
  },
  {
    id: 'tianjin',
    name: 'Tianjin',
    country: 'China',
    latitude: 39.0842,
    longitude: 117.2,
    coverage: ['O'],
  },
  {
    id: 'chongqing',
    name: 'Chongqing',
    country: 'China',
    latitude: 29.4316,
    longitude: 106.9123,
    coverage: ['O'],
  },
  {
    id: 'dalian',
    name: 'Dalian',
    country: 'China',
    latitude: 38.914,
    longitude: 121.6147,
    coverage: ['S'],
  },
  {
    id: 'futian-shenzhen',
    name: 'Futian, Shenzhen',
    country: 'China',
    latitude: 22.541,
    longitude: 114.055,
    coverage: ['S'],
  },
  {
    id: 'fuzhou-foc',
    name: 'Fuzhou',
    country: 'China',
    code: 'FOC',
    latitude: 26.0745,
    longitude: 119.2965,
    coverage: ['S'],
  },
  {
    id: 'nanjing-nkg',
    name: 'Nanjing',
    country: 'China',
    code: 'NKG',
    latitude: 32.0603,
    longitude: 118.7969,
    coverage: ['S'],
  },
  {
    id: 'shekou-shenzhen',
    name: 'Shekou, Shenzhen',
    country: 'China',
    latitude: 22.486,
    longitude: 113.918,
    coverage: ['S'],
  },
  {
    id: 'yantian-shenzhen',
    name: 'Yantian, Shenzhen',
    country: 'China',
    latitude: 22.556,
    longitude: 114.236,
    coverage: ['S'],
  },
  {
    id: 'xingang-tianjin',
    name: 'Xingang / Tianjin Port',
    country: 'China',
    latitude: 38.986,
    longitude: 117.75,
    coverage: ['S'],
  },

  {
    id: 'tokyo-tyo',
    name: 'Tokyo',
    country: 'Japan',
    code: 'TYO',
    latitude: 35.6762,
    longitude: 139.6503,
    coverage: ['O', 'S', 'D'],
  },
  {
    id: 'narita-nrt',
    name: 'Narita',
    country: 'Japan',
    code: 'NRT',
    latitude: 35.772,
    longitude: 140.3929,
    coverage: ['S', 'N'],
  },
  {
    id: 'osaka-osa',
    name: 'Osaka',
    country: 'Japan',
    code: 'OSA',
    latitude: 34.6937,
    longitude: 135.5023,
    coverage: ['S', 'D'],
  },
  {
    id: 'kobe',
    name: 'Kobe',
    country: 'Japan',
    latitude: 34.6901,
    longitude: 135.1955,
    coverage: ['S'],
  },
  {
    id: 'nagoya',
    name: 'Nagoya',
    country: 'Japan',
    latitude: 35.1815,
    longitude: 136.9066,
    coverage: ['S'],
  },
  {
    id: 'moji-kitakyushu',
    name: 'Moji / Kitakyushu',
    country: 'Japan',
    latitude: 33.8834,
    longitude: 130.8752,
    coverage: ['S'],
  },
  {
    id: 'yokohama',
    name: 'Yokohama',
    country: 'Japan',
    latitude: 35.4437,
    longitude: 139.638,
    coverage: ['S'],
  },
  {
    id: 'seoul',
    name: 'Seoul',
    country: 'South Korea',
    latitude: 37.5665,
    longitude: 126.978,
    coverage: ['O'],
  },
  {
    id: 'incheon-icn',
    name: 'Incheon',
    country: 'South Korea',
    code: 'ICN',
    latitude: 37.4563,
    longitude: 126.7052,
    coverage: ['S'],
  },
  {
    id: 'busan-pus',
    name: 'Busan',
    country: 'South Korea',
    code: 'PUS',
    latitude: 35.1796,
    longitude: 129.0756,
    coverage: ['D'],
  },

  {
    id: 'singapore-sin',
    name: 'Singapore',
    country: 'Singapore',
    code: 'SIN',
    latitude: 1.3521,
    longitude: 103.8198,
    coverage: ['O', 'S', 'D', 'N'],
  },
  {
    id: 'kuala-lumpur-kul',
    name: 'Kuala Lumpur',
    country: 'Malaysia',
    code: 'KUL',
    latitude: 3.139,
    longitude: 101.6869,
    coverage: ['O', 'S'],
  },
  {
    id: 'johor',
    name: 'Johor',
    country: 'Malaysia',
    latitude: 1.4927,
    longitude: 103.7414,
    coverage: ['S'],
  },
  {
    id: 'penang',
    name: 'Penang',
    country: 'Malaysia',
    latitude: 5.4141,
    longitude: 100.3288,
    coverage: ['S'],
  },
  {
    id: 'port-klang',
    name: 'Port Klang',
    country: 'Malaysia',
    latitude: 3,
    longitude: 101.4,
    coverage: ['S'],
  },
  {
    id: 'ho-chi-minh-sgn',
    name: 'Ho Chi Minh City',
    country: 'Vietnam',
    code: 'SGN',
    latitude: 10.8231,
    longitude: 106.6297,
    coverage: ['O', 'S', 'D', 'N'],
  },
  {
    id: 'hai-phong',
    name: 'Hai Phong',
    country: 'Vietnam',
    latitude: 20.8449,
    longitude: 106.6881,
    coverage: ['O', 'S'],
  },
  {
    id: 'hanoi',
    name: 'Hanoi',
    country: 'Vietnam',
    latitude: 21.0278,
    longitude: 105.8342,
    coverage: ['O'],
  },
  {
    id: 'jakarta-jkt',
    name: 'Jakarta',
    country: 'Indonesia',
    code: 'JKT',
    latitude: -6.2088,
    longitude: 106.8456,
    coverage: ['O', 'S', 'D', 'N'],
  },
  {
    id: 'bangkok-bkk',
    name: 'Bangkok',
    country: 'Thailand',
    code: 'BKK',
    latitude: 13.7563,
    longitude: 100.5018,
    coverage: ['O', 'S', 'D'],
  },
  {
    id: 'laem-chabang',
    name: 'Laem Chabang',
    country: 'Thailand',
    latitude: 13.0827,
    longitude: 100.883,
    coverage: ['O'],
  },
  {
    id: 'phnom-penh',
    name: 'Phnom Penh',
    country: 'Cambodia',
    latitude: 11.5564,
    longitude: 104.9282,
    coverage: ['O'],
  },
  {
    id: 'sihanoukville',
    name: 'Sihanoukville',
    country: 'Cambodia',
    latitude: 10.6275,
    longitude: 103.5221,
    coverage: ['O'],
  },
  {
    id: 'bavet',
    name: 'Bavet',
    country: 'Cambodia',
    latitude: 11.067,
    longitude: 106.1,
    coverage: ['O'],
  },
  {
    id: 'yangon',
    name: 'Yangon',
    country: 'Myanmar',
    latitude: 16.8409,
    longitude: 96.1735,
    coverage: ['O'],
  },
  {
    id: 'mumbai',
    name: 'Mumbai',
    country: 'India',
    latitude: 19.076,
    longitude: 72.8777,
    coverage: ['O'],
  },
  {
    id: 'nhava-sheva-jnpt',
    name: 'Nhava Sheva / JNPT',
    country: 'India',
    latitude: 18.9499,
    longitude: 72.9512,
    coverage: ['S'],
  },
  {
    id: 'manila',
    name: 'Manila',
    country: 'Philippines',
    latitude: 14.5995,
    longitude: 120.9842,
    coverage: ['S'],
  },

  {
    id: 'sydney-syd',
    name: 'Sydney',
    country: 'Australia',
    code: 'SYD',
    latitude: -33.8688,
    longitude: 151.2093,
    coverage: ['S', 'D', 'N'],
  },
  {
    id: 'dubai-dxb',
    name: 'Dubai',
    country: 'United Arab Emirates',
    code: 'DXB',
    latitude: 25.2048,
    longitude: 55.2708,
    coverage: ['D'],
  },
  {
    id: 'riyadh-ruh',
    name: 'Riyadh',
    country: 'Saudi Arabia',
    code: 'RUH',
    latitude: 24.7136,
    longitude: 46.6753,
    coverage: ['N'],
  },

  {
    id: 'united-kingdom',
    name: 'United Kingdom',
    country: 'United Kingdom',
    latitude: 54.5,
    longitude: -3.4,
    coverage: ['O'],
  },
  {
    id: 'london-lhr',
    name: 'London / Heathrow',
    country: 'United Kingdom',
    code: 'LHR',
    latitude: 51.5074,
    longitude: -0.1278,
    coverage: ['S', 'N'],
  },
  {
    id: 'southampton-sou',
    name: 'Southampton',
    country: 'United Kingdom',
    code: 'SOU',
    latitude: 50.9097,
    longitude: -1.4044,
    coverage: ['D'],
  },
  {
    id: 'paris-cdg',
    name: 'Paris / Charles de Gaulle',
    country: 'France',
    code: 'CDG',
    latitude: 48.8566,
    longitude: 2.3522,
    coverage: ['N'],
  },
  {
    id: 'le-havre-leh',
    name: 'Le Havre',
    country: 'France',
    code: 'LEH / FRLEH',
    latitude: 49.4944,
    longitude: 0.1079,
    coverage: ['D'],
  },
  {
    id: 'amsterdam-ams',
    name: 'Amsterdam',
    country: 'Netherlands',
    code: 'AMS',
    latitude: 52.3676,
    longitude: 4.9041,
    coverage: ['S', 'N'],
  },
  {
    id: 'frankfurt-fra',
    name: 'Frankfurt',
    country: 'Germany',
    code: 'FRA',
    latitude: 50.1109,
    longitude: 8.6821,
    coverage: ['S', 'N'],
  },
  {
    id: 'hamburg-ham',
    name: 'Hamburg',
    country: 'Germany',
    code: 'HAM',
    latitude: 53.5511,
    longitude: 9.9937,
    coverage: ['D'],
  },
  {
    id: 'athens-ath',
    name: 'Athens',
    country: 'Greece',
    code: 'ATH',
    latitude: 37.9838,
    longitude: 23.7275,
    coverage: ['N'],
  },
  {
    id: 'prague-prg',
    name: 'Prague',
    country: 'Czech Republic',
    code: 'PRG',
    latitude: 50.0755,
    longitude: 14.4378,
    coverage: ['N'],
  },
  {
    id: 'moscow-mow',
    name: 'Moscow',
    country: 'Russia',
    code: 'MOW',
    latitude: 55.7558,
    longitude: 37.6173,
    coverage: ['N'],
  },
  {
    id: 'vladivostok-vvo',
    name: 'Vladivostok',
    country: 'Russia',
    code: 'VVO',
    latitude: 43.1155,
    longitude: 131.8855,
    coverage: ['D'],
  },

  {
    id: 'cape-town',
    name: 'Cape Town',
    country: 'South Africa',
    latitude: -33.9249,
    longitude: 18.4241,
    coverage: ['S'],
  },
  {
    id: 'durban-dur',
    name: 'Durban',
    country: 'South Africa',
    code: 'DUR',
    latitude: -29.8587,
    longitude: 31.0218,
    coverage: ['S', 'D'],
  },
  {
    id: 'johannesburg-jnb',
    name: 'Johannesburg',
    country: 'South Africa',
    code: 'JNB',
    latitude: -26.2041,
    longitude: 28.0473,
    coverage: ['S', 'N'],
  },

  {
    id: 'los-angeles-lax',
    name: 'Los Angeles',
    country: 'United States',
    code: 'LAX',
    latitude: 34.0522,
    longitude: -118.2437,
    coverage: ['O', 'S', 'D', 'N'],
  },
  {
    id: 'new-york-nyc-jfk',
    name: 'New York',
    country: 'United States',
    code: 'NYC / JFK',
    latitude: 40.7128,
    longitude: -74.006,
    coverage: ['O', 'S', 'D', 'N'],
  },
  {
    id: 'chicago-chi-ord',
    name: 'Chicago',
    country: 'United States',
    code: 'CHI / ORD',
    latitude: 41.8781,
    longitude: -87.6298,
    coverage: ['O', 'S', 'D', 'N'],
  },
  {
    id: 'san-francisco',
    name: 'San Francisco',
    country: 'United States',
    latitude: 37.7749,
    longitude: -122.4194,
    coverage: ['O', 'S'],
  },
  {
    id: 'miami',
    name: 'Miami',
    country: 'United States',
    latitude: 25.7617,
    longitude: -80.1918,
    coverage: ['S'],
  },
  {
    id: 'seattle',
    name: 'Seattle',
    country: 'United States',
    latitude: 47.6062,
    longitude: -122.3321,
    coverage: ['S'],
  },
  {
    id: 'san-diego-san',
    name: 'San Diego',
    country: 'United States',
    code: 'SAN',
    latitude: 32.7157,
    longitude: -117.1611,
    coverage: ['N'],
  },
  {
    id: 'toronto',
    name: 'Toronto',
    country: 'Canada',
    latitude: 43.6532,
    longitude: -79.3832,
    coverage: ['S'],
  },
  {
    id: 'montreal',
    name: 'Montreal',
    country: 'Canada',
    latitude: 45.5019,
    longitude: -73.5674,
    coverage: ['S'],
  },
  {
    id: 'vancouver',
    name: 'Vancouver',
    country: 'Canada',
    latitude: 49.2827,
    longitude: -123.1207,
    coverage: ['S'],
  },
  {
    id: 'mexico',
    name: 'Mexico',
    country: 'Mexico',
    latitude: 23.6345,
    longitude: -102.5528,
    coverage: ['O'],
    countryLevel: true,
  },
  {
    id: 'mexico-city-mex',
    name: 'Mexico City',
    country: 'Mexico',
    code: 'MEX',
    latitude: 19.4326,
    longitude: -99.1332,
    coverage: ['N'],
  },

  {
    id: 'sao-paulo-gru',
    name: 'São Paulo / Guarulhos',
    country: 'Brazil',
    code: 'GRU',
    latitude: -23.5505,
    longitude: -46.6333,
    coverage: ['N'],
  },
  {
    id: 'ecuador',
    name: 'Ecuador',
    country: 'Ecuador',
    latitude: -1.8312,
    longitude: -78.1834,
    coverage: ['O'],
    countryLevel: true,
  },
];
