export const COVERAGE_CODES = ['O', 'D', 'G', 'W'] as const;

export type CoverageCode = (typeof COVERAGE_CODES)[number];

export type GlobalServiceLocation = {
  id: string;
  name: string;
  country: string;
  state?: string;
  code?: string;
  latitude: number;
  longitude: number;
  coverage: readonly CoverageCode[];
  regionLevel?: boolean;
};

export const GLOBAL_SERVICE_LOCATIONS: readonly GlobalServiceLocation[] = [
  {
    id: 'melbourne',
    name: 'Melbourne',
    country: 'Australia',
    latitude: -37.8136,
    longitude: 144.9631,
    coverage: ['G'],
  },
  {
    id: 'sydney',
    name: 'Sydney',
    country: 'Australia',
    code: 'SYD',
    latitude: -33.8688,
    longitude: 151.2093,
    coverage: ['D', 'G'],
  },
  {
    id: 'bavet',
    name: 'Bavet',
    country: 'Cambodia',
    latitude: 11.067,
    longitude: 106.1,
    coverage: ['O'],
  },
  {
    id: 'phnom-penh',
    name: 'Phnom Penh',
    country: 'Cambodia',
    latitude: 11.5564,
    longitude: 104.9282,
    coverage: ['O', 'W'],
  },
  {
    id: 'sihanoukville',
    name: 'Sihanoukville',
    country: 'Cambodia',
    latitude: 10.6275,
    longitude: 103.5221,
    coverage: ['O'],
  },
  {
    id: 'ningbo',
    name: 'Ningbo',
    country: 'China',
    latitude: 29.8683,
    longitude: 121.544,
    coverage: ['O', 'W'],
  },
  {
    id: 'chengdu',
    name: 'Chengdu',
    country: 'China',
    latitude: 30.5728,
    longitude: 104.0668,
    coverage: ['W'],
  },
  {
    id: 'chongqing',
    name: 'Chongqing',
    country: 'China',
    latitude: 29.4316,
    longitude: 106.9123,
    coverage: ['O'],
  },
  {
    id: 'dalian',
    name: 'Dalian',
    country: 'China',
    latitude: 38.914,
    longitude: 121.6147,
    coverage: ['G'],
  },
  {
    id: 'dongguan',
    name: 'Dongguan',
    country: 'China',
    latitude: 23.0207,
    longitude: 113.7518,
    coverage: ['O', 'W'],
  },
  {
    id: 'foshan',
    name: 'Foshan',
    country: 'China',
    latitude: 23.0215,
    longitude: 113.1214,
    coverage: ['O', 'W'],
  },
  {
    id: 'shenzhen',
    name: 'Shenzhen',
    country: 'China',
    code: 'SZX',
    latitude: 22.5431,
    longitude: 114.0579,
    coverage: ['O', 'G', 'W'],
  },
  {
    id: 'fuzhou',
    name: 'Fuzhou',
    country: 'China',
    latitude: 26.0745,
    longitude: 119.2965,
    coverage: ['W'],
  },
  {
    id: 'guangzhou',
    name: 'Guangzhou',
    country: 'China',
    latitude: 23.1291,
    longitude: 113.2644,
    coverage: ['O'],
  },
  {
    id: 'kunming',
    name: 'Kunming',
    country: 'China',
    latitude: 25.0389,
    longitude: 102.7183,
    coverage: ['W'],
  },
  {
    id: 'kunshan',
    name: 'Kunshan',
    country: 'China',
    latitude: 31.3798,
    longitude: 120.9787,
    coverage: ['W'],
  },
  {
    id: 'nanjing',
    name: 'Nanjing',
    country: 'China',
    latitude: 32.0603,
    longitude: 118.7969,
    coverage: ['G'],
  },
  {
    id: 'shanghai',
    name: 'Shanghai',
    country: 'China',
    code: 'PVG',
    latitude: 31.2304,
    longitude: 121.4737,
    coverage: ['O', 'G', 'W'],
  },
  {
    id: 'qingdao',
    name: 'Qingdao',
    country: 'China',
    latitude: 36.0671,
    longitude: 120.3826,
    coverage: ['O', 'G'],
  },
  {
    id: 'suzhou',
    name: 'Suzhou',
    country: 'China',
    latitude: 31.2989,
    longitude: 120.5853,
    coverage: ['O'],
  },
  {
    id: 'tianjin',
    name: 'Tianjin',
    country: 'China',
    latitude: 39.0842,
    longitude: 117.2,
    coverage: ['O', 'G', 'W'],
  },
  {
    id: 'wujiang',
    name: 'Wujiang',
    country: 'China',
    latitude: 31.1592,
    longitude: 120.6453,
    coverage: ['G'],
  },
  {
    id: 'wuxi',
    name: 'Wuxi',
    country: 'China',
    latitude: 31.49,
    longitude: 120.3119,
    coverage: ['W'],
  },
  {
    id: 'xiamen',
    name: 'Xiamen',
    country: 'China',
    latitude: 24.4798,
    longitude: 118.0894,
    coverage: ['O', 'G', 'W'],
  },
  {
    id: 'zhongshan',
    name: 'Zhongshan',
    country: 'China',
    latitude: 22.5176,
    longitude: 113.3928,
    coverage: ['O'],
  },
  {
    id: 'hong-kong',
    name: 'Hong Kong',
    country: 'Hong Kong',
    code: 'HKG',
    latitude: 22.3193,
    longitude: 114.1694,
    coverage: ['O', 'D', 'G', 'W'],
  },
  {
    id: 'mumbai',
    name: 'Mumbai',
    country: 'India',
    latitude: 19.076,
    longitude: 72.8777,
    coverage: ['O'],
  },
  {
    id: 'cibitung-bekasi',
    name: 'Cibitung Bekasi',
    country: 'Indonesia',
    latitude: -6.2447,
    longitude: 107.1364,
    coverage: ['W'],
  },
  {
    id: 'gresik',
    name: 'Gresik',
    country: 'Indonesia',
    latitude: -7.156,
    longitude: 112.6524,
    coverage: ['W'],
  },
  {
    id: 'jakarta',
    name: 'Jakarta',
    country: 'Indonesia',
    code: 'JKT',
    latitude: -6.2088,
    longitude: 106.8456,
    coverage: ['O', 'D', 'G'],
  },
  {
    id: 'chiba',
    name: 'Chiba',
    country: 'Japan',
    latitude: 35.6073,
    longitude: 140.1063,
    coverage: ['W'],
  },
  {
    id: 'osaka',
    name: 'Osaka',
    country: 'Japan',
    code: 'OSA',
    latitude: 34.6937,
    longitude: 135.5023,
    coverage: ['D', 'G', 'W'],
  },
  {
    id: 'tokyo',
    name: 'Tokyo',
    country: 'Japan',
    code: 'NRT / TYO',
    latitude: 35.6762,
    longitude: 139.6503,
    coverage: ['O', 'D', 'G', 'W'],
  },
  {
    id: 'yokohama',
    name: 'Yokohama',
    country: 'Japan',
    latitude: 35.4437,
    longitude: 139.638,
    coverage: ['G'],
  },
  {
    id: 'kedah',
    name: 'Kedah',
    country: 'Malaysia',
    latitude: 6.1184,
    longitude: 100.3685,
    coverage: ['W'],
    regionLevel: true,
  },
  {
    id: 'kuala-lumpur',
    name: 'Kuala Lumpur',
    country: 'Malaysia',
    latitude: 3.139,
    longitude: 101.6869,
    coverage: ['O'],
  },
  {
    id: 'port-klang',
    name: 'Port Klang',
    country: 'Malaysia',
    latitude: 3.0,
    longitude: 101.4,
    coverage: ['G'],
  },
  {
    id: 'selangor',
    name: 'Selangor',
    country: 'Malaysia',
    latitude: 3.0738,
    longitude: 101.5183,
    coverage: ['W'],
    regionLevel: true,
  },
  {
    id: 'yangon',
    name: 'Yangon',
    country: 'Myanmar',
    latitude: 16.8409,
    longitude: 96.1735,
    coverage: ['O'],
  },
  {
    id: 'manila',
    name: 'Manila',
    country: 'Philippines',
    latitude: 14.5995,
    longitude: 120.9842,
    coverage: ['G'],
  },
  {
    id: 'singapore',
    name: 'Singapore',
    country: 'Singapore',
    code: 'SIN',
    latitude: 1.3521,
    longitude: 103.8198,
    coverage: ['O', 'D', 'G', 'W'],
  },
  {
    id: 'busan',
    name: 'Busan',
    country: 'South Korea',
    code: 'PUS',
    latitude: 35.1796,
    longitude: 129.0756,
    coverage: ['D', 'G'],
  },
  {
    id: 'incheon',
    name: 'Incheon',
    country: 'South Korea',
    latitude: 37.4563,
    longitude: 126.7052,
    coverage: ['G', 'W'],
  },
  {
    id: 'seoul',
    name: 'Seoul',
    country: 'South Korea',
    latitude: 37.5665,
    longitude: 126.978,
    coverage: ['O', 'W'],
  },
  {
    id: 'colombo',
    name: 'Colombo',
    country: 'Sri Lanka',
    latitude: 6.9271,
    longitude: 79.8612,
    coverage: ['G'],
  },
  {
    id: 'taichung',
    name: 'Taichung',
    country: 'Taiwan',
    latitude: 24.1477,
    longitude: 120.6736,
    coverage: ['O', 'W'],
  },
  {
    id: 'hsinchu',
    name: 'Hsinchu',
    country: 'Taiwan',
    latitude: 24.8339,
    longitude: 121.0125,
    coverage: ['O', 'W'],
  },
  {
    id: 'kaohsiung',
    name: 'Kaohsiung',
    country: 'Taiwan',
    latitude: 22.6273,
    longitude: 120.3014,
    coverage: ['O', 'W'],
  },
  {
    id: 'keelung',
    name: 'Keelung',
    country: 'Taiwan',
    latitude: 25.1276,
    longitude: 121.7392,
    coverage: ['W'],
  },
  {
    id: 'taoyuan',
    name: 'Taoyuan',
    country: 'Taiwan',
    latitude: 24.9937,
    longitude: 121.301,
    coverage: ['O', 'W'],
  },
  {
    id: 'tainan',
    name: 'Tainan',
    country: 'Taiwan',
    latitude: 22.9997,
    longitude: 120.227,
    coverage: ['O', 'W'],
  },
  {
    id: 'taipei',
    name: 'Taipei',
    country: 'Taiwan',
    code: 'TPE',
    latitude: 25.033,
    longitude: 121.5654,
    coverage: ['O', 'G', 'W'],
  },
  {
    id: 'bangkok',
    name: 'Bangkok',
    country: 'Thailand',
    code: 'BKK',
    latitude: 13.7563,
    longitude: 100.5018,
    coverage: ['O', 'D', 'G'],
  },
  {
    id: 'bangkrabang',
    name: 'Bangkrabang',
    country: 'Thailand',
    latitude: 13.7269,
    longitude: 100.7712,
    coverage: ['O'],
  },
  {
    id: 'laem-chabang',
    name: 'Laem Chabang',
    country: 'Thailand',
    latitude: 13.0827,
    longitude: 100.883,
    coverage: ['W'],
  },
  {
    id: 'rayong',
    name: 'Rayong',
    country: 'Thailand',
    latitude: 12.6833,
    longitude: 101.2372,
    coverage: ['W'],
  },
  {
    id: 'binh-duong',
    name: 'Binh Duong',
    country: 'Vietnam',
    latitude: 10.9804,
    longitude: 106.6519,
    coverage: ['W'],
    regionLevel: true,
  },
  {
    id: 'da-nang',
    name: 'Da Nang',
    country: 'Vietnam',
    latitude: 16.0544,
    longitude: 108.2022,
    coverage: ['W'],
  },
  {
    id: 'haiphong',
    name: 'Haiphong',
    country: 'Vietnam',
    latitude: 20.8449,
    longitude: 106.6881,
    coverage: ['O'],
  },
  {
    id: 'hanoi',
    name: 'Hanoi',
    country: 'Vietnam',
    latitude: 21.0278,
    longitude: 105.8342,
    coverage: ['O', 'W'],
  },
  {
    id: 'ho-chi-minh-city',
    name: 'Ho Chi Minh City',
    country: 'Vietnam',
    code: 'SGN',
    latitude: 10.8231,
    longitude: 106.6297,
    coverage: ['O', 'D', 'G', 'W'],
  },
  {
    id: 'montreal',
    name: 'Montreal',
    country: 'Canada',
    latitude: 45.5019,
    longitude: -73.5674,
    coverage: ['G'],
  },
  {
    id: 'toronto',
    name: 'Toronto',
    country: 'Canada',
    latitude: 43.6532,
    longitude: -79.3832,
    coverage: ['G'],
  },
  {
    id: 'manzanillo',
    name: 'Manzanillo',
    country: 'Mexico',
    latitude: 19.1128,
    longitude: -104.3383,
    coverage: ['W'],
  },
  {
    id: 'mexico-city',
    name: 'Mexico City',
    country: 'Mexico',
    code: 'MEX',
    latitude: 19.4326,
    longitude: -99.1332,
    coverage: ['O', 'G'],
  },
  {
    id: 'silao',
    name: 'Silao',
    country: 'Mexico',
    latitude: 20.9427,
    longitude: -101.4283,
    coverage: ['W'],
  },
  {
    id: 'atlanta',
    name: 'Atlanta',
    country: 'United States',
    state: 'GA',
    latitude: 33.749,
    longitude: -84.388,
    coverage: ['W'],
  },
  {
    id: 'auburn',
    name: 'Auburn',
    country: 'United States',
    state: 'WA',
    latitude: 47.3073,
    longitude: -122.2285,
    coverage: ['W'],
  },
  {
    id: 'buena-park',
    name: 'Buena Park',
    country: 'United States',
    state: 'CA',
    latitude: 33.8675,
    longitude: -117.9981,
    coverage: ['W'],
  },
  {
    id: 'chicago',
    name: 'Chicago',
    country: 'United States',
    state: 'IL',
    code: 'CHI / ORD',
    latitude: 41.8781,
    longitude: -87.6298,
    coverage: ['O', 'D', 'G'],
  },
  {
    id: 'college-park',
    name: 'College Park',
    country: 'United States',
    state: 'GA',
    latitude: 33.6407,
    longitude: -84.4277,
    coverage: ['W'],
  },
  {
    id: 'compton',
    name: 'Compton',
    country: 'United States',
    state: 'CA',
    latitude: 33.8958,
    longitude: -118.2201,
    coverage: ['W'],
  },
  {
    id: 'cranbury',
    name: 'Cranbury',
    country: 'United States',
    state: 'NJ',
    latitude: 40.314,
    longitude: -74.5127,
    coverage: ['W'],
  },
  {
    id: 'dallas',
    name: 'Dallas',
    country: 'United States',
    state: 'TX',
    latitude: 33.0198,
    longitude: -96.6989,
    coverage: ['O'],
  },
  {
    id: 'houston',
    name: 'Houston',
    country: 'United States',
    state: 'TX',
    latitude: 29.7604,
    longitude: -95.3698,
    coverage: ['O'],
  },
  {
    id: 'livonia',
    name: 'Livonia',
    country: 'United States',
    state: 'MI',
    latitude: 42.3684,
    longitude: -83.3527,
    coverage: ['W'],
  },
  {
    id: 'los-angeles',
    name: 'Los Angeles',
    country: 'United States',
    state: 'CA',
    code: 'LAX',
    latitude: 34.0522,
    longitude: -118.2437,
    coverage: ['O', 'D', 'G'],
  },
  {
    id: 'miami',
    name: 'Miami',
    country: 'United States',
    state: 'FL',
    latitude: 25.7617,
    longitude: -80.1918,
    coverage: ['G'],
  },
  {
    id: 'new-york',
    name: 'New York',
    country: 'United States',
    state: 'NY',
    code: 'JFK / NYC',
    latitude: 40.7128,
    longitude: -74.006,
    coverage: ['O', 'D', 'G'],
  },
  {
    id: 'robbinsville',
    name: 'Robbinsville',
    country: 'United States',
    state: 'NJ',
    latitude: 40.214,
    longitude: -74.6032,
    coverage: ['W'],
  },
  {
    id: 'san-diego',
    name: 'San Diego',
    country: 'United States',
    state: 'CA',
    code: 'SAN',
    latitude: 32.7157,
    longitude: -117.1611,
    coverage: ['G'],
  },
  {
    id: 'san-francisco',
    name: 'San Francisco',
    country: 'United States',
    state: 'CA',
    latitude: 37.7749,
    longitude: -122.4194,
    coverage: ['O', 'G', 'W'],
  },
  {
    id: 'seattle',
    name: 'Seattle',
    country: 'United States',
    state: 'WA',
    latitude: 47.6062,
    longitude: -122.3321,
    coverage: ['G'],
  },
  {
    id: 'west-warwick',
    name: 'West Warwick',
    country: 'United States',
    state: 'RI',
    latitude: 41.6996,
    longitude: -71.5245,
    coverage: ['W'],
  },
  {
    id: 'antwerp',
    name: 'Antwerp',
    country: 'Belgium',
    latitude: 51.2194,
    longitude: 4.4025,
    coverage: ['G'],
  },
  {
    id: 'dobrenice',
    name: 'Dobřenice',
    country: 'Czech Republic',
    latitude: 50.1667,
    longitude: 15.7,
    coverage: ['W'],
  },
  {
    id: 'mlada-boleslav',
    name: 'Mladá Boleslav',
    country: 'Czech Republic',
    latitude: 50.4111,
    longitude: 14.9028,
    coverage: ['W'],
  },
  {
    id: 'prague',
    name: 'Prague',
    country: 'Czech Republic',
    code: 'PRG',
    latitude: 50.0755,
    longitude: 14.4378,
    coverage: ['G'],
  },
  {
    id: 'cerveny-kostelec',
    name: 'Červený Kostelec',
    country: 'Czech Republic',
    latitude: 50.4667,
    longitude: 16.0833,
    coverage: ['W'],
  },
  {
    id: 'aarhus',
    name: 'Aarhus',
    country: 'Denmark',
    latitude: 56.1629,
    longitude: 10.2039,
    coverage: ['G'],
  },
  {
    id: 'copenhagen',
    name: 'Copenhagen',
    country: 'Denmark',
    latitude: 55.6761,
    longitude: 12.5683,
    coverage: ['G'],
  },
  {
    id: 'grand-couronne',
    name: 'Grand-Couronne',
    country: 'France',
    latitude: 49.35,
    longitude: 1.0,
    coverage: ['W'],
  },
  {
    id: 'le-havre',
    name: 'Le Havre',
    country: 'France',
    code: 'LEH',
    latitude: 49.4944,
    longitude: 0.1079,
    coverage: ['D', 'G'],
  },
  {
    id: 'moissy-cramayel',
    name: 'Moissy-Cramayel',
    country: 'France',
    latitude: 48.6167,
    longitude: 2.6167,
    coverage: ['W'],
  },
  {
    id: 'paris',
    name: 'Paris',
    country: 'France',
    code: 'CDG',
    latitude: 48.8566,
    longitude: 2.3522,
    coverage: ['G'],
  },
  {
    id: 'sainte-luce-sur-loire',
    name: 'Sainte-Luce-sur-Loire',
    country: 'France',
    latitude: 47.25,
    longitude: -1.4333,
    coverage: ['W'],
  },
  {
    id: 'dusseldorf',
    name: 'Düsseldorf',
    country: 'Germany',
    latitude: 51.2277,
    longitude: 6.7735,
    coverage: ['W'],
  },
  {
    id: 'frankfurt',
    name: 'Frankfurt',
    country: 'Germany',
    code: 'FRA',
    latitude: 50.1109,
    longitude: 8.6821,
    coverage: ['G'],
  },
  {
    id: 'hamburg',
    name: 'Hamburg',
    country: 'Germany',
    code: 'HAM',
    latitude: 53.5511,
    longitude: 9.9937,
    coverage: ['D', 'G'],
  },
  {
    id: 'muhlenhagen',
    name: 'Muhlenhagen',
    country: 'Germany',
    latitude: 53.535,
    longitude: 10.01,
    coverage: ['W'],
  },
  {
    id: 'reinbek',
    name: 'Reinbek',
    country: 'Germany',
    latitude: 53.5167,
    longitude: 10.25,
    coverage: ['W'],
  },
  {
    id: 'seelenkamp',
    name: 'Seelenkamp',
    country: 'Germany',
    latitude: 52.1667,
    longitude: 9.0,
    coverage: ['W'],
  },
  {
    id: 'athens',
    name: 'Athens',
    country: 'Greece',
    code: 'ATH',
    latitude: 37.9838,
    longitude: 23.7275,
    coverage: ['G'],
  },
  {
    id: 'albrandswaard',
    name: 'Albrandswaard',
    country: 'Netherlands',
    latitude: 51.85,
    longitude: 4.4,
    coverage: ['W'],
  },
  {
    id: 'amsterdam',
    name: 'Amsterdam',
    country: 'Netherlands',
    code: 'AMS',
    latitude: 52.3676,
    longitude: 4.9041,
    coverage: ['G'],
  },
  {
    id: 'eindhoven',
    name: 'Eindhoven',
    country: 'Netherlands',
    latitude: 51.4416,
    longitude: 5.4697,
    coverage: ['W'],
  },
  {
    id: 'nijmegen',
    name: 'Nijmegen',
    country: 'Netherlands',
    latitude: 51.8425,
    longitude: 5.8528,
    coverage: ['W'],
  },
  {
    id: 'rotterdam',
    name: 'Rotterdam',
    country: 'Netherlands',
    latitude: 51.9244,
    longitude: 4.4777,
    coverage: ['G', 'W'],
  },
  {
    id: 'mazowiecki',
    name: 'Mazowiecki',
    country: 'Poland',
    latitude: 52.2297,
    longitude: 21.0122,
    coverage: ['W'],
    regionLevel: true,
  },
  {
    id: 'pabianice',
    name: 'Pabianice',
    country: 'Poland',
    latitude: 51.664,
    longitude: 19.3542,
    coverage: ['W'],
  },
  {
    id: 'sochaczew',
    name: 'Sochaczew',
    country: 'Poland',
    latitude: 52.2333,
    longitude: 20.2333,
    coverage: ['W'],
  },
  {
    id: 'zabia-wola',
    name: 'Żabia Wola',
    country: 'Poland',
    latitude: 52.0333,
    longitude: 20.5333,
    coverage: ['W'],
  },
  {
    id: 'moscow',
    name: 'Moscow',
    country: 'Russia',
    code: 'MOW',
    latitude: 55.7558,
    longitude: 37.6173,
    coverage: ['G'],
  },
  {
    id: 'saint-petersburg',
    name: 'Saint Petersburg',
    country: 'Russia',
    latitude: 59.9311,
    longitude: 30.3609,
    coverage: ['G'],
  },
  {
    id: 'vladivostok',
    name: 'Vladivostok',
    country: 'Russia',
    code: 'VVO',
    latitude: 43.1155,
    longitude: 131.8855,
    coverage: ['D', 'G'],
  },
  {
    id: 'gothenburg',
    name: 'Gothenburg',
    country: 'Sweden',
    latitude: 57.7089,
    longitude: 11.9746,
    coverage: ['G'],
  },
  {
    id: 'crayford',
    name: 'Crayford',
    country: 'United Kingdom',
    latitude: 51.4453,
    longitude: 0.1783,
    coverage: ['W'],
  },
  {
    id: 'felixstowe',
    name: 'Felixstowe',
    country: 'United Kingdom',
    latitude: 51.9639,
    longitude: 1.3518,
    coverage: ['G'],
  },
  {
    id: 'london',
    name: 'London',
    country: 'United Kingdom',
    code: 'LHR',
    latitude: 51.5074,
    longitude: -0.1278,
    coverage: ['O', 'G'],
  },
  {
    id: 'manchester',
    name: 'Manchester',
    country: 'United Kingdom',
    latitude: 53.4808,
    longitude: -2.2426,
    coverage: ['W'],
  },
  {
    id: 'south-ockendon',
    name: 'South Ockendon',
    country: 'United Kingdom',
    latitude: 51.5167,
    longitude: 0.2917,
    coverage: ['W'],
  },
  {
    id: 'southampton',
    name: 'Southampton',
    country: 'United Kingdom',
    code: 'SOU',
    latitude: 50.9097,
    longitude: -1.4044,
    coverage: ['D', 'G'],
  },
  {
    id: 'weybridge',
    name: 'Weybridge',
    country: 'United Kingdom',
    latitude: 51.3733,
    longitude: -0.4567,
    coverage: ['W'],
  },
  {
    id: 'riyadh',
    name: 'Riyadh',
    country: 'Saudi Arabia',
    code: 'RUH',
    latitude: 24.7136,
    longitude: 46.6753,
    coverage: ['G'],
  },
  {
    id: 'dubai',
    name: 'Dubai',
    country: 'United Arab Emirates',
    code: 'DXB',
    latitude: 25.2048,
    longitude: 55.2708,
    coverage: ['D', 'G'],
  },
  {
    id: 'durban',
    name: 'Durban',
    country: 'South Africa',
    code: 'DUR',
    latitude: -29.8587,
    longitude: 31.0218,
    coverage: ['D', 'G'],
  },
  {
    id: 'johannesburg',
    name: 'Johannesburg',
    country: 'South Africa',
    code: 'JNB',
    latitude: -26.2041,
    longitude: 28.0473,
    coverage: ['G'],
  },
  {
    id: 'sao-paulo',
    name: 'São Paulo',
    country: 'Brazil',
    code: 'GRU',
    latitude: -23.4356,
    longitude: -46.4731,
    coverage: ['G'],
  },
  {
    id: 'guayaquil',
    name: 'Guayaquil',
    country: 'Ecuador',
    latitude: -2.1894,
    longitude: -79.8891,
    coverage: ['O'],
  },
];
